# Generated by Django 5.2.14 on 2026-06-22 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(default='뉴시스', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'news',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_stocks', to='news.news')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_stocks', to='stocks.stock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('news', 'stock'), name='unique_news_stock')],
            },
        ),
        migrations.CreateModel(
            name='NewsTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_reason', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_themes', to='news.news')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_themes', to='stocks.theme')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('news', 'theme'), name='unique_news_theme')],
            },
        ),
    ]
