# Generated by Django 5.2.14 on 2026-05-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, unique=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('market', models.CharField(choices=[('KOSPI', '유가'), ('KOSDAQ', '코스닥'), ('KONEX', '코넥스')], max_length=10)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('main_product', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
