# Generated by Django 5.2.14 on 2026-06-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewritten_content', models.TextField()),
                ('sentiment', models.CharField(max_length=20)),
                ('impact_score', models.FloatField()),
                ('impact_reason', models.TextField()),
                ('difficult_terms', models.JSONField(blank=True, null=True)),
                ('check_points', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='news.news')),
            ],
        ),
    ]
