# Generated by Django 5.2.14 on 2026-06-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='highlight',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='sentiment_reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
