# Generated by Django 5.2.14 on 2026-06-24 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('terms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userterm',
            name='unique_user_term',
        ),
        migrations.AddField(
            model_name='userterm',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_terms', to='news.news'),
        ),
        migrations.AddConstraint(
            model_name='userterm',
            constraint=models.UniqueConstraint(fields=('user', 'term', 'news'), name='unique_user_term_news'),
        ),
    ]
