# Generated by Django 5.2.14 on 2026-06-22 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, unique=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('market', models.CharField(choices=[('KOSPI', '유가'), ('KOSDAQ', '코스닥'), ('KONEX', '코넥스')], max_length=10)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('main_product', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_relations', to='stocks.stock')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_relations', to='stocks.theme')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock', 'theme'), name='unique_stock_theme')],
            },
        ),
    ]
